[Feat] 선택 키워드 기반 연관 키워드 계산 API 구현
boostcampwm-2022/web17-waglewagle pull request #70
Opened 2022-11-23 18:44 UTC by HodaeSsi

# 💻 결과물
- 키워드 기반, 연관 키워드 요청 API
```
request : GET /api/v1/keyword/associations?keyword-id={string}
response :
{
  keywordId: string,
  keywordName: string,
  rank: number
}[]
```

# 🏗️ 작업배경

- 키워드 하나에 대해, 같은 커뮤니티 내에서 연관성이 높은 다른 키워드들을 반환해주는 API
- 이번 주 데모를 위해, 알고리즘은 가장 간단한 방식으로 구현해 놓음 (추후 알고리즘 교체 및 최적화)

# 📝 작업내용

- JPQL, QueryDSL을 이용하여 쿼리문 작성 (프로젝트에 QueryDSL 의존성 추가)
- 연관관계 계산 객체, `AssociationCalculator` 스프링 빈으로 등록

# 🤔 고민사항

- DTO객체 생성 및 관리 방법
- 더 나은 연관관계 키워드 계산 알고리즘 (협업 필터링 학습중)
- 구현 관련 기술에 대한 학습정리 (코드 주석 정리)

# 🔜 다음 예정 작업

- 커뮤니티내 전체 키워드 조회 API 작성

Closes #43

2022-11-24 05:34 UTC, aaa22220304 requested changes
정렬 알고리즘만 수정하면 좋을 것 같습니다!
수고하셨습니다.

2022-11-24 05:34 UTC, aaa22220304 commented on rest/src/main/java/com/waglewagle/rest/keyword/Keyword.java
> +    //TODO: 안썼다! >> keywordUserRepository쓰지 말고 keywordUser를 keyword로 부터 접근하라던데...
TODO 는 필요 작업과 이유를 적어주시면 좋을 것 같아용

2022-11-24 05:34 UTC, aaa22220304 commented on rest/src/main/java/com/waglewagle/rest/keyword/KeywordService.java
> +    //TODO: 읽기만하는데도 @transactional이 필요할까???
@Transactional(readOnly = true)로 readonly임을 명시할 수 있습니다.
성능과 관련해서 이점이 있는 것으로 알고 있습니다.
단, update나 persist가 이루어져도 반영되지 않는 것으로 알고 있습니다.
https://willseungh0.tistory.com/75

2022-11-24 05:34 UTC, aaa22220304 commented on rest/src/main/java/com/waglewagle/rest/keyword/association/DumbAssociateCalculator.java
> +    public List<AssociationDTO> getSortedKeywordList(Keyword baseKeyword, List<Keyword> associatedKeywords) {
List<Keyword>를 반환하지 않는데, getSortedKeywordList라는 함수가 반환되어 헷갈릴 여지가 있는 것 같습니다.

2022-11-24 05:34 UTC, aaa22220304 commented on rest/src/main/java/com/waglewagle/rest/keyword/association/DumbAssociateCalculator.java
> +            if (!Objects.equals(baseKeyword.getKeyword(), associatedKeywords.get(i).getKeyword())) {
associatedKeywords.get(i).getKeyword()) 이 친구가 3번 반복되는데, 따로 변수로 뺄 여지가 충분한 것 같습니다.

2022-11-24 05:34 UTC, aaa22220304 commented on rest/src/main/java/com/waglewagle/rest/keyword/association/DumbAssociateCalculator.java
> +            new AssociationDTO(
static 함수로 DTO를 만드는 함수를 빼거나, 인자들이 조금 더 단순화 될 수 있는 구조면 더 좋을 것 같습니다!

2022-11-24 05:34 UTC, aaa22220304 commented on rest/src/main/java/com/waglewagle/rest/keyword/association/DumbAssociateCalculator.java
> +        for (int i = 1; i < keyList.size(); i++) {
정렬 알고리즘 수정이 필요한 것 같습니다.

2022-11-24 05:36 UTC, HodaeSsi commented on rest/src/main/java/com/waglewagle/rest/keyword/association/DumbAssociateCalculator.java
> +        for (int i = 1; i < keyList.size(); i++) {
ㅎㅎㅈㅅ!

2022-11-24 19:16 UTC, vangona approved these changes

2022-11-27 04:57 UTC, vangona commented on rest/src/main/java/com/waglewagle/rest/keyword/KeywordController.java
> +        return ResponseEntity.ok(sortedList);
DB 읽기 실패나 유효하지 않은 keyword-id를 param으로 받은 경우가 있지 않을까요??

2022-11-27 04:57 UTC, vangona commented on rest/src/main/java/com/waglewagle/rest/keyword/KeywordRepository.java
> +                .fetch(); //TODO: fetch? fetchJoin?
fetchJoin이 뭔지 해서 찾아봤는데, N+1 문제를 해결하기 위해서 연관된 엔티티도 같이 읽는 것이군요

2022-11-27 04:57 UTC, vangona commented on rest/src/main/java/com/waglewagle/rest/keyword/association/DumbAssociateCalculator.java
> +        Deque<AssociationDTO> dq = new LinkedList<>();
자료구조 지원해주는거 너무 부럽네요

2022-11-27 04:57 UTC, vangona commented on rest/src/main/java/com/waglewagle/rest/keyword/association/DumbAssociateCalculator.java
> +            if (countMap.get(keyList.get(i)) > countMap.get(dq.getFirst().getKeywordName())) {
가나다 순까지 백엔드에서 맞춰서 보내주시는군요...! 감사합니다

2022-11-27 04:57 UTC, vangona commented on rest/src/main/java/com/waglewagle/rest/keyword/association/DumbAssociateCalculator.java
> +            if (!Objects.equals(baseKeyword.getKeyword(), associatedKeywords.get(i).getKeyword())) {
승민님 코딩 스타일 저랑 진짜 비슷하시네요

2022-11-27 04:57 UTC, vangona commented on rest/src/main/java/com/waglewagle/rest/keyword/association/DumbAssociateCalculator.java
> +                mapping.put(associatedKeywords.get(i).getKeyword(), associatedKeywords.get(i));
혹시 월요일날 현재 dumb 알고리즘 코드와 함께 한 번 만 설명 부탁드려도 될까요??
설명 들으면서 알고리즘을 읽으면 스프링 읽는 능력도 더 향상될 것 같아서요!

2022-11-27 11:07 UTC, closed without merging